language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install -g codecov istanbul

script:
  - codecov
  - npm run test

after_success:
  - chmod +x ./send_build_results.sh
  - ./send_build_results.sh success $WEBHOOK_URL
after_failure:
  - chmod +x ./send_build_results.sh
  - ./send_build_results.sh failure $WEBHOOK_URL
