#!/usr/bin/env sh

curl "https://classicdb.ch/?item=$1" > "res/test/classicdb_$2.html"
curl "https://tbcdb.com/?item=$1" > "res/test/tbcdb_$2.html"

echo "    $2: {"
echo "        classicdb: fs.readFileSync(\"res/test/classicdb_$2.html\").toString(),"
echo "        tbcdb: fs.readFileSync(\"res/test/tbcdb_$2.html\").toString(),"
echo "    },"
echo ""
echo "            it(\"parses X from classicdb.ch item page source\", async () => {"
echo "                const parser = new SlotTypeParser(item_page_sources.$2.classicdb);"
echo "                const result = await parser.parse();"
echo "                expect(result.type).toBe(Type.);"
echo "            });"

