version: "3.7"

services:
  classicdb_bot:
    container_name: classicdb-bot
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: npm run start
    env_file:
      - .env
    depends_on:
      - classicdb_bot_db
    networks:
      - classicdb_bot

  classicdb_bot_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - classicdb_bot

networks:
  classicdb_bot:
