export declare type ItemSlot =
    | "Shirt"
    | "Two-Hand"
    | "Chest"
    | "Legs"
    | "Feet"
    | "Main Hand"
    | "Hands"
    | "Non-equippable"
    | "One-Hand"
    | "Wrist"
    | "Trinket"
    | "Bag"
    | "Waist"
    | "Finger"
    | "Off Hand"
    | "Held In Off-hand"
    | "Back"
    | "Relic"
    | "Head"
    | "Neck"
    | "Shoulder"
    | "Ranged"
    | "Ammo"
    | "Tabard"
    | "Thrown";
