export declare type ItemSubClass =
    | "Miscellaneous"
    | "Staff"
    | "Cloth"
    | "Leather"
    | "Axe"
    | "Sword"
    | "Potion"
    | "Mace"
    | "Quest"
    | "Food & Drink"
    | "Junk"
    | "Meat"
    | "Cooking"
    | "Mail"
    | "Herb"
    | "Dagger"
    | "Bag"
    | "Simple"
    | "Parts"
    | "Consumable"
    | "Shield"
    | "Other"
    | "Scroll"
    | "Book"
    | "Mount"
    | "Bandage"
    | "Polearm"
    | "Gun"
    | "Quiver"
    | "Ammo Pouch"
    | "Item Enhancement"
    | "Leatherworking"
    | "Elixir"
    | "Bow"
    | "Arrow"
    | "Bullet"
    | "Alchemy"
    | "Tailoring"
    | "Key"
    | "Metal & Stone"
    | "Blacksmithing"
    | "Reagent"
    | "Fist Weapon"
    | "Explosives"
    | "Devices"
    | "Engineering"
    | "Pet"
    | "Wand"
    | "Enchanting"
    | "Fishing Pole"
    | "Crossbow"
    | "First Aid"
    | "Elemental"
    | "Plate"
    | "Flask"
    | "Fishing"
    | "Holiday"
    | "Jewelcrafting"
    | "Soul Bag"
    | "Enchanting Bag"
    | "Orange"
    | "Herb Bag"
    | "Totem"
    | "Libram"
    | "Idol"
    | "Prismatic"
    | "Green"
    | "Red"
    | "Purple"
    | "Yellow"
    | "Blue"
    | "Materials"
    | "Engineering Bag"
    | "Gem Bag"
    | "Thrown"
    | "Meta"
    | "Mining Bag"
    | "Exotic"
    | "Leatherworking Bag";
